# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170123_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
